import type { GetStaticProps } from "next";
import type { Bootcamp } from "@/types";

import Head from "next/head";
import { Link } from "@/components";
import { bootcampService } from "@/services";

interface Props {
  bootcamps: Bootcamp[];
}

export default function Home({ bootcamps }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-4xl px-4 mx-auto">
        <h2 className="mb-2 text-xl font-bold">Bootcamps</h2>

        <div className="grid gap-1 md:grid-cols-3 sm:grid-cols-2">
          {bootcamps.map((bootcamp) => (
            <Link key={bootcamp.id} href={`/courses/${bootcamp.id}`}>
              {bootcamp.title}
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const bootcamps = await bootcampService.getAll();
  return { props: { bootcamps } };
};
